# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Djava.net.preferIPv4Stack=true

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.9

# Mod Properties
mod_version=1.0.0
maven_group=night
archives_base_name=Nightix

# Dependencies
fabric_version=0.119.2+1.21.4

# Локальные runtime-либы
media_player_info_version=0.1.0
kotlin_version=1.9.20
kotlinx_serialization_version=1.6.3

bundle_libs_in_jar=true
